version: "3.9"

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - database
    environment:
      DATABASE_URL: mysql://root:${DB_PASS}@database:3306/prisma
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run seeder && npx tsx src/bin/www.ts"

  database:
    image: mysql:8
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: prisma
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
