version: "3.9"
services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: npx tsx ./src/bin/www.ts
